myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns=[
    path('index/',views.index,name="index"),
    path('courses/',views.courses,name="courses"),
    path('aboutus/',views.aboutus,name="aboutus"),
    path('enquiry/',views.enquiry,name="enquiry"),
    path('batches/',views.batches,name="batches"),
]

pro1/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myapp.urls")),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render

# Create your views here.
name="PYSPIDERS"
email="pyspiders@gmail.com"
phno="9966206473"
def index(request):
    return render(request,"home.html",{'name':name})
def courses(request):
    return render(request,"courses.html",{'name':name})
def aboutus (request):
    return render(request,"aboutus.html",{"name": name,"email":email,"phno":phno})
def enquiry (request):
    return render(request,"enquiry.html",{"name": name,"email":email,"phno":phno})
def batches(request):
    return render(request,"batches.html",{"name": name,"email":email,"phno":phno})

templates/aboutus.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>ABOUTUS PAGE</title>
{% endblock %}

{% block content %}
<center>
    <br><br>
    <img src="{% static 'images/img.jpg.crdownload' %}" alt="pyspider team" width="100" height="100">
    <link rel="stylesheet" href="{% static  'css/style.css' %}">
    <h1>NAME : {{name}}</h1>
    <h2>EMAIL :{{email}}</h2>
    <h2>PHNO : {{phno}}</h2>
    <p>PySpiders is a best-in-class learning solutions organization headquartered in India’s IT capital, Bangalore. We offer a wide range of courses in the area of Python development.</p>
</center>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>BASE PAGE</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static  'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</head>
<body>

    {% include "partials/_navbar.html" %}
    <!-- body -->
    <div class="container">
        <div class="jumbotron">
            {% block content %}
          
            {% endblock %}
        </div>

    </div>
        
    {% include "partials/_footer.html" %}
    


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</body>

templates/batches.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>batches</title>
    <center>
        <caption><u>BATCHES</u></caption><br>
        <thead>Upcoming Batches of Courses around the Globe</thead><br><br>
    </head>
    </center>

<body>
    <body>
        <div class="container"></div>
        <form action="https://pyspiders.com/batches" type="GET">
            <label for="name"> subject:</label>
            <input type="text" id="subject" name="subject" placeholder=" search by subject..">
            <label for="course"> course:</label>
            <input type="text" id="course" name="course" placeholder=" search by course..">
            <label for="name"> batch date:</label>
            <input type="date" id="date" name="branch date" placeholder=" search by branch date..">
            <label for="name"> branch:</label>
            <input type="text" id="branch" name="branch" placeholder=" search by branch..">
            <input type="reset" value="reset"><br><br>
            <label for="name"> Total number of batches:</label>
            <select>
                <option>....select...</option>
                <option>fast track</option>
                <option>python</option>
            </select><br><br>
            <center>
                <tfoot>batch not available?<br>
                    We do undertake Special and Fast-track Batches, please contact us at <label for ="email" value="email"></label>{{email}}:</tfoot>
            </center>
      </div>
    
</body>
</html>

templates/courses.html
{% extends "base.html" %}
{% load static %}


{% block title %}
    <title>COURSES PAGE</title>
{% endblock %}

{% block content %}
<center>
    <br><br>
    <img src="{% static 'images/IMG2.png' %}" alt="best learning courses" width="75" height="100"><br>
    <h1>{{name}}</h1><br>
    <h2>The best selection of python courses</h2><br>
    Search Courses:<input type="text" name="search courses" placeholder="search courses">
    <h5>python full stack</h5>
    <h5>testing</h5>
    <h5>data science</h5>
    <h5>apptitude</h5>
    <h5>c,c++ programming</h5>
</center>
{% endblock %}

templates/enquiry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>enquiry</title>
    <center>
       <strong><u>ENQUIRY</u></strong> <br><br>
    </center>
   
</head>
<body>
    <div class="container"></div>
    <form action="https://www.pyspiders.com" type="GET">
  
        <label for="name"> Name</label>
        <input type="text" id="fname" name="name" placeholder=" enter Your name..">
        <label for="phone no"> phone no</label>
        <input type="number" id="phone no" name="phone no" placeholder=" enter phone no..">
        <label for="name"> email</label>
        <input type="email" id="email" name="email" placeholder=" email..">
        <label for="name"> message</label>
        <input type="text" id="msg" name="msg" placeholder=" type msg here..">
        <label for="name"> submit</label>
        <input type="submit" value="Submit">
    </form>
  </div>
  </body>
  </html>

templates/home.html
{% extends "base.html" %}
{% load static %}


{% block title %}
    <title>HOME PAGE</title>
{% endblock %}

{% block content %}
<center><img src="{% static 'images/IMG2.png' %}" alt="best learning courses" width="75" height="100">
<h1>WELCOME TO {{name}}</h1>
</center>
{% endblock %}

templates/partials/_footer.html
<!-- FOOTER -->
<div class="footer-basic">
    <footer>
        <br>
        <center><p class="copyright">PYSPIDERS © 2021</p></center>
    </footer>
</div>

templates/partials/_navbar.html
<!-- NAV BAR -->
<ul class="nav nav-tabs">
    <li class="nav-item">
      {% if request.path == "" %}
      <a class="nav-link active" aria-current="page" href="{% url 'myapp:index' %}">HOME</a>
      {% else %}
      <a class="nav-link eactiv" aria-current="page" href="{% url 'myapp:index' %}">HOME</a>
      {% endif %}
      
      
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'myapp:courses' %}">COURSES</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'myapp:aboutus' %}">ABOUTUS</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:enquiry' %}">ENQUIRY</a>
      </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:batches' %}">BATCHES</a>
      </li>

  </ul>